version: "3.8"

services:
  # db:
  #   container_name: nest-clean-pg
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: docker
  #     POSTGRES_DB: nest-clean
  #     PGDATA: /data/postgres
  #   volumes:
  #     - ./data/pg:/data/postgres
  
  cache:
    container_name: nest-clean-cache
    image: redis
    ports:
      - 6380:6379
    volumes:
      - ./data/regis:/data